disabled_rules :
 - line_length
 - type_body_length
 - trailing_whitespace
 - colon
 - comma
 - control_statement
 - trailing_newline
 - identifier_name
 - mark
 - multiple_closures_with_trailing_closure
 - vertical_whitespace
 - for_where
 - force_cast
excluded :
 - Pods 
